# yaml-language-server: $schema=https://raw.githubusercontent.com/codemod/codemod/refs/heads/main/schemas/workflow.json

version: "1"

nodes:
  - id: migrate-next-to-start
    name: Migrate Next.js To TanStack Start
    type: automatic
    steps:
      - name: Apply deterministic TS/TSX transforms
        js-ast-grep:
          js_file: scripts/codemod.ts
          language: "tsx"
          params:
            routesDirectory: "{{ routesDirectory }}"
            routes_directory: "{{ routes_directory }}"
